### ISSUE TITLE
Release checklist

### ISSUE THREAD

**Issue by GuusLieben** [Dockbox-OSS/Hartshorn#228]
## Plugins to replace
_Format: original plugin/extension -> new module_

**darwinserver-sponge-e1ebcd5-2020-05-25-all.jar**
- [x] OldPlots -> OldPlots
- [x] WorldUnloader -> World Management
- [x] Archival -> Archiving
- [x] GoToLobby -> World Management
- [x] Spectator Teleport -> Player Actions
- [x] WorldUnloader -> World Management
- [x] Dave -> Dave

**EndPortal-1.0-SNAPSHOT.jar**
- [x] EndPortal -> Player Actions

**PlotEntityInteraction-2.0.3-API-7.jar**
- [x] Entity Interaction -> Player Actions
