### ISSUE TITLE
Documentation tracker - Cache

### ISSUE THREAD

**Issue by GuusLieben** [Dockbox-OSS/Hartshorn#810]
This document tracks the documentation progress of Hartshorn Cache (`hartshorn-cache`). 

- [x] `org.dockbox.hartshorn.cache.Cache`
- [x] `org.dockbox.hartshorn.cache.CacheFactory`
- [x] `org.dockbox.hartshorn.cache.CacheManager`
- [ ] `org.dockbox.hartshorn.cache.CacheManagerImpl`
- [x] `org.dockbox.hartshorn.cache.CacheProviders`
- [x] `org.dockbox.hartshorn.cache.Expiration`
- [x] `org.dockbox.hartshorn.cache.HashCodeKeyGenerator`
- [x] `org.dockbox.hartshorn.cache.KeyGenerator`
- [x] `org.dockbox.hartshorn.cache.annotations.CacheDecorator`
- [x] `org.dockbox.hartshorn.cache.annotations.CacheService`
- [ ] `org.dockbox.hartshorn.cache.annotations.Cached`
- [ ] `org.dockbox.hartshorn.cache.annotations.EvictCache`
- [ ] `org.dockbox.hartshorn.cache.annotations.Expire`
- [ ] `org.dockbox.hartshorn.cache.annotations.UpdateCache`
- [ ] `org.dockbox.hartshorn.cache.annotations.UseCaching`
- [x] `org.dockbox.hartshorn.cache.caffeine.CaffeineCache`
- [x] `org.dockbox.hartshorn.cache.caffeine.CaffeineProviders`
- [x] `org.dockbox.hartshorn.cache.context.CacheContext`
- [x] `org.dockbox.hartshorn.cache.context.CacheContextImpl`
- [x] `org.dockbox.hartshorn.cache.context.CacheMethodContext`
- [x] `org.dockbox.hartshorn.cache.context.CacheMethodContextImpl`
- [x] `org.dockbox.hartshorn.cache.modifiers.CacheEvictionMethodPostProcessor`
- [ ] `org.dockbox.hartshorn.cache.modifiers.CacheServicePostProcessor`
- [x] `org.dockbox.hartshorn.cache.modifiers.CacheUpdateMethodPostProcessor`
- [x] `org.dockbox.hartshorn.cache.modifiers.CachedMethodPostProcessor`
- [ ] `org.dockbox.hartshorn.cache.modifiers.UnavailableCacheException`

**Comment by GuusLieben** [comment]
No longer applicable after #977. When module(s) are re-introduced in a future release they'll receive appropricate specification.
