### ISSUE TITLE
Documentation tracker - Commands

### ISSUE THREAD

**Issue by GuusLieben** [Dockbox-OSS/Hartshorn#811]
This document tracks the documentation progress of Hartshorn Commands (`hartshorn-commands`). 

- [ ] `org.dockbox.hartshorn.commands.ApplicationSystemSubject`
- [ ] `org.dockbox.hartshorn.commands.CommandBeanListener`
- [ ] `org.dockbox.hartshorn.commands.CommandExecutor`
- [x] `org.dockbox.hartshorn.commands.CommandGateway`
- [ ] `org.dockbox.hartshorn.commands.CommandGatewayImpl`
- [ ] `org.dockbox.hartshorn.commands.CommandListener`
- [ ] `org.dockbox.hartshorn.commands.CommandListenerImpl`
- [x] `org.dockbox.hartshorn.commands.CommandParser`
- [ ] `org.dockbox.hartshorn.commands.CommandParserImpl`
- [ ] `org.dockbox.hartshorn.commands.CommandParameterResources`
- [ ] `org.dockbox.hartshorn.commands.CommandProviders`
- [x] `org.dockbox.hartshorn.commands.CommandSource`
- [ ] `org.dockbox.hartshorn.commands.CommandResources`
- [ ] `org.dockbox.hartshorn.commands.InvalidExecutorException`
- [x] `org.dockbox.hartshorn.commands.ParsingException`
- [ ] `org.dockbox.hartshorn.commands.SystemSubject`
- [ ] `org.dockbox.hartshorn.commands.annotations.Command`
- [ ] `org.dockbox.hartshorn.commands.annotations.Cooldown`
- [ ] `org.dockbox.hartshorn.commands.annotations.Parameter`
- [ ] `org.dockbox.hartshorn.commands.annotations.UseCommands`
- [x] `org.dockbox.hartshorn.commands.arguments.ArgumentConverterImpl`
- [ ] `org.dockbox.hartshorn.commands.arguments.ArgumentMatchingFailedException`
- [ ] `org.dockbox.hartshorn.commands.arguments.CommandContextParameterRule`
- [ ] `org.dockbox.hartshorn.commands.arguments.CommandParameterLoader`
- [ ] `org.dockbox.hartshorn.commands.arguments.CommandParameterLoaderContext`
- [ ] `org.dockbox.hartshorn.commands.arguments.CommandSubjectParameterRule`
- [ ] `org.dockbox.hartshorn.commands.arguments.CustomParameterPattern`
- [ ] `org.dockbox.hartshorn.commands.arguments.DefaultArgumentConverter`
- [ ] `org.dockbox.hartshorn.commands.arguments.DefaultArgumentConverters`
- [ ] `org.dockbox.hartshorn.commands.arguments.DynamicPatternConverter`
- [x] `org.dockbox.hartshorn.commands.arguments.HashtagParameterPattern`
- [ ] `org.dockbox.hartshorn.commands.arguments.MissingConverterException`
- [ ] `org.dockbox.hartshorn.commands.arguments.PrefixedParameterPattern`
- [x] `org.dockbox.hartshorn.commands.context.ArgumentConverterContext`
- [x] `org.dockbox.hartshorn.commands.context.CommandContext`
- [ ] `org.dockbox.hartshorn.commands.context.CommandContextImpl`
- [x] `org.dockbox.hartshorn.commands.context.CommandDefinitionContext`
- [-] `org.dockbox.hartshorn.commands.context.CommandDefinitionContextImpl`
- [x] `org.dockbox.hartshorn.commands.context.CommandExecutorContext`
- [x] `org.dockbox.hartshorn.commands.context.CommandParameterContext`
- [ ] `org.dockbox.hartshorn.commands.context.DefinitionContextLostException`
- [ ] `org.dockbox.hartshorn.commands.context.IllegalArgumentRequestException`
- [ ] `org.dockbox.hartshorn.commands.context.MethodCommandExecutorContext`
- [x] `org.dockbox.hartshorn.commands.context.ParserContext`
- [x] `org.dockbox.hartshorn.commands.definition.ArgumentConverter`
- [x] `org.dockbox.hartshorn.commands.definition.CommandDefinition`
- [x] `org.dockbox.hartshorn.commands.definition.CommandElement`
- [ ] `org.dockbox.hartshorn.commands.definition.CommandElementImpl`
- [x] `org.dockbox.hartshorn.commands.definition.CommandFlag`
- [x] `org.dockbox.hartshorn.commands.definition.CommandFlagElement`
- [ ] `org.dockbox.hartshorn.commands.definition.CommandFlagImpl`
- [x] `org.dockbox.hartshorn.commands.definition.CommandPartial`
- [ ] `org.dockbox.hartshorn.commands.definition.EnumCommandElement`
- [ ] `org.dockbox.hartshorn.commands.definition.GroupCommandElement`
- [ ] `org.dockbox.hartshorn.commands.events.CommandEvent`
- [ ] `org.dockbox.hartshorn.commands.events.CommandEvent$After`
- [ ] `org.dockbox.hartshorn.commands.events.CommandEvent$Before`
- [x] `org.dockbox.hartshorn.commands.extension.CommandExecutorExtension`
- [ ] `org.dockbox.hartshorn.commands.extension.CommandExtensionContext`
- [x] `org.dockbox.hartshorn.commands.extension.CooldownExtension`
- [x] `org.dockbox.hartshorn.commands.extension.ExtensionResult`
- [ ] `org.dockbox.hartshorn.commands.service.CommandParameterValidator`
- [x] `org.dockbox.hartshorn.commands.service.CommandParameters`
- [ ] `org.dockbox.hartshorn.commands.service.CommandServiceScanner`
